### ISSUE TITLE
Unit test failure with some exceptions

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-filter-grok#15]
Rspec test fail with this outcome

```
  logstash-filter-grok git:(master) bundle exec rspec
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :broken=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.......................
An error occurred in an after hook
  NoMethodError: undefined method `unlink' for nil:NilClass
  occurred at /Users/purbon/work/purbon/infra_tools/clones/logstash-filter-grok/spec/filters/grok_spec.rb:692:in `(root)'

F.......................................................
An error occurred in an after hook
  NoMethodError: undefined method `unlink' for nil:NilClass
  occurred at /Users/purbon/work/purbon/infra_tools/clones/logstash-filter-grok/spec/filters/grok_spec.rb:667:in `(root)'

F....

Failures:

  1) LogStash::Filters::Grok patterns in custom dir override those in 'patterns/' dir "{"message":"0"}" when processed
     Failure/Error: Unable to find matching line from backtrace
     IOError:
       No such file or directory
     # ./spec/filters/grok_spec.rb:679:in `(root)'

  2) LogStash::Filters::Grok patterns in the 'patterns/' dir override core patterns "{"message":"hello"}" when processed
     Failure/Error: Unable to find matching line from backtrace
     IOError:
       No such file or directory
     # ./spec/filters/grok_spec.rb:653:in `(root)'

Finished in 3.59 seconds
84 examples, 2 failures

Failed examples:

rspec /Users/purbon/.rvm/gems/jruby-1.7.16.1@filter-grok/gems/logstash-devutils-0.0.10-java/lib/logstash/devutils/rspec/logstash_helpers.rb:51 # LogStash::Filters::Grok patterns in custom dir override those in 'patterns/' dir "{"message":"0"}" when processed
rspec /Users/purbon/.rvm/gems/jruby-1.7.16.1@filter-grok/gems/logstash-devutils-0.0.10-java/lib/logstash/devutils/rspec/logstash_helpers.rb:51 # LogStash::Filters::Grok patterns in the 'patterns/' dir override core patterns "{"message":"hello"}" when processed

Randomized with seed 36915
```

More info on http://build-eu-00.elasticsearch.org/view/LS%20Filters/job/logstash_filter_grok_commit/338/console

**Comment by talevy** [comment]
build is passing now: https://travis-ci.org/logstash-plugins/logstash-filter-grok
